### ISSUE TITLE
Triaged Tasks and Features

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1028]
**This is a collection of tasks and features I intend to focus on** in the order I plan to work on them. I desire to accomplish everything eventually, but this list helps me to arrange near-term priorities. Previous triage issues: #651, #412.

<details open>
<summary><h2>Primary Focus (June, 2022)</h2></summary>

* #1888

</details>

<details>
<summary><h2>Primary Focus (March, 2022)</h2></summary>

* ScottPlot 4.1 is stable. Focus on maintenance and bug fixes (do not aggressively add features).

* ScottPlot 5.0 is early in development. Wait for `Microsoft.Maui.Graphics` to mature and stabalize before aggressively resuming development. See comments in #1647 for considerations and next steps.

* As ScottPlot 5 matures, focus on improving the website and documentation

</details>

<details>
<summary><h2>Primary Focus (February, 2022)</h2></summary>

* I enacted a soft feature freeze to allow me to focus on ScottPlot 5
  * #1624
  * #1647

</details>

<details>
<summary><h2>Primary Focus (November, 2021)</h2></summary>

* **Maintenance:** Rapidly address or close issues/PRs to concentrate effort on these high priority goals

* **Abstract the Rendering System:** Work toward #1036 while [Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics) continues to mature (release targeted for Q2, 2022)

* **Refactor TickCollection** to improve performance, reliability, and add support for advanced tick features:
  * #725
  * #925
  * #926 
  * #475 
  * #469 
  * #935 
  * #648 
  * #644 
  * #926 6 
  * #1070 
  * #926
</details>

<details>
<summary><h2>Triaged Tasks and Features</h2></summary>

_This list will be reviewed and re-categorized as the primary focus tasks above have are accomplished_

### Get ScottPlot 4.1 out of Beta
- [x] Modernize demo application (#887)
- [x] Fix mouse events and make enter/leave demo (#999)
- [x] Fix offset and multiplier notation (#1026)
- [x] Improve design-time appearance of WpfPlot (#1043)
- [x] Improve support and documentation for queued rendering (#1034)
- [x] set up DocFX for API documentation (#1047)
- [x] Update documents to describe ScottPlot 4.1 (#949, #966)
- [x] add FAQ page describing 4.0 to 4.1 changes ([link](https://swharden.com/scottplot/faq/version-4.1/))
- [x] Remove the beta/pre-release designation and release ScottPlot 4.1 on NuGet (#715)

### High Priority / Next Release
- [x] Move the [ScottPlot Overview](https://swharden.com/scottplot/overview/) into the FAQ and update for 4.1
- [x] Add plottable drag/drop events and mark old names obsolete (#1072)
- [x] Hide the design time error message in WPF control by default(#1073)
- [x] Add rendering test for font detection (#1079)
- [x] Fix/refactor color palette system (#1058, #1082)
- [x] Add options to exclude axis lines and spans from automatic axis calculations (#999, #1083)
- [x] Add bitmap interpolation to heatmaps (#1003, #1085)
- [x] Fix bug causing `Configuration.RenderIfPlottableCountChanges` to be ignored (#1087)
- [x] Improve automatic rendering based on unique plottables instead of count (#1087)
- [x] Add crosshair axis label (#999)
- [x] Fix bug affecting reset and delayed rendering (#1098, #1099)
- [x] Allow tick relabeling with `Axis.SetCustomLabelFunction(func<double, string> func)` (#1070, #926)
- [x] Fix AxisAutoX and AxisAutoY (#1089)

### High Priority
- [ ] Add a "how to contribute a code modification" section that describes git/PRs to contributing.md (#1092)
- [ ] Ensure all [Q&A Discussions](https://github.com/ScottPlot/ScottPlot/discussions/categories/q-a) have marked answers
- [x] Step mode for signal plots (#1092)
- [ ] Individual coloring of bars in bar plots (#1071)
- [ ] Add methods to make it easier to add live data to scatter, signal, bar, and finance plots. This may or may not involve a data object to manage array resizing and data validation. (#815, #841, #827, #1042)
- [ ] Scatter plots should be able to plot data with gaps (#976)
- [ ] Refactor markers to allow custom markers and additional marker options (#386, #784, #785, #786)
- [ ] Break the `Tools` class into smaller classes. Move statistical logic out of histogram class and improve names and documentation in the histogram class. (#930, #932, #934, #624)
- [ ] Create a `Generate` class with functions with more logical and better documented function signatures than `DataGen` (#902, #903)
- [ ] Consider using a double-buffering system (#1388)
- [ ] BarPlot should accept an array of Bar objects to allow bars to be individually customized (#1071)
* **Hacktoberfest:** Prepare for #1274
* **Devops:** Automate package deployment
  - [x] Move CI from Azure Pipelines to GitHub Actions
  - [x] GitHub releases trigger package deployment to NuGet
  - [x] Start using [ScottPlot.NET](https://scottplot.net) ([ScottPlot.NET repository](https://github.com/ScottPlot/ScottPlot.NET))
  - [x] GitHub releases generate and deploy cookbook and demo app
- [ ] Controls: mappable keys and buttons (#1354, #1335)

### Moderate Priority
- [ ] Improve async rendering support and documentation/demonstration of the render queue (#736, #761, #813)
- [ ] Improve API consistency for deep styling options (#981)
- [ ] Consider using nullable annotations #691
- [x] Improve the heatmap plot type [project 1](https://github.com/orgs/ScottPlot/projects/1), #666, #667, #701, #707, #713
- [ ] Clean the `/dev` folder and move meta content to the ScottPlot website
- [ ] Prevent obsolete plot methods from being browsable (#963)
- [ ] Document how to create custom plot types on the FAQ page (#973)
- [ ] Revisit error checking and validation to see if that behavior should be stripped/changed (#940, #553)
- [ ] Create architecture.md
- [ ] Support deep copying of plots. This may require allowing deep copies of all styling and plottable classes. (#819, #1010)
- [x] Axis label for mouse crosshair (#999)
- [x] The style system should use classes or structs not enums (#1291, #1299)
- [ ] Improve multiplot support (#1137)
- [ ] Refactor back-end to use abstracted buttons (make it easy to change what buttons do, #1222)
- [ ] Colorbar: get value under cursor #1494
- [ ] Detect mouse events in axis area #1601
- [ ] Create a package to plot DataFrames and improve notebook features #1825

### Plottable
- [ ] Add options to customize location of L-shaped scale bar (#363)
- [ ] Extend the legend to support horizontal orientation or columns (#580)
- [ ] Add legend options to place it outside the plot area (#1279)
- [x] Fix histogram calculations and add tests that assert bins/counts are identical to those calculated with python and numpy/matplotlib (#1051)
- [ ] OHLC bars should show values in a tooltip when the mouse is near them (#696). When this is added it seems useful to make a static class with static methods for drawing tooltips, and it can simply be called from any plottable which needs a tooltip drawn.
- [ ] Improve efficiency of scatter plot point distance measurements (#709)
- [ ] Wiggle plot (#450)
- [ ] Dendrogram (#987)
- [ ] Consider having scatter plots treat NaN as breaks in the line (#1161)
- [ ] Components like markers, lines, and errorbars should be reusable
- [ ] Heatmap: row/column labels, cell value labels, and palette support (#1273, #420)
- [ ] Coxcomb: non-linear (square root) scaling (#1450)
- [ ] Population: full vs. half box-and-whisker (#1440)
- [ ] Violin Plot (#1301)
- [ ] Bracket (#1302)
- [ ] TreeMap (#1479)
- [ ] ScatterPlot should have a `ScatterPlotBase` and reduce duplicate code across all the different types of scatter plots (#1422)
- [ ] MultipleLineSeries plot (#1579)
- [ ] Strip charts: #1551
- [x] Forest plot: #1552
- [ ] BarSeries: #1749
- [ ] Background: #1867

### Documentation
- [ ] Create a Finance Demo (not a cookbook example, but a full demo program) to consolidate common finance-related tasks in one program. This demo should describe how to add live incoming data (#395, #403, #637)
- [ ] Work toward enabling [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) at the project level
- [x] Consider using traditional documentation generators (#903)
- [ ] Document how to change mouse button functionality (e.g., middle-click-drag pan, #352)

</details>

**Comment by chrisxfire** [comment]
@swharden re #1825 I have been using DataFrames in Python (Pandas) for several years, and in C# (Microsoft.Data.Analysis) for about a year.  I am happy to help with this item any way I can.  However, my skills in C# are not nearly as developed as yours.  I'm still actively learning the language and the corresponding framework.

**Comment by swharden** [comment]
ScottPlot 4 is stable, and does not require addition of major features as this time. 

The triaged list of goals on this page is great, and will remain documented here.

I will shift my focus toward only addressing issues/PRs as they are opened, and try to give all my remaining effort to finishing ScottPlot 5 (#1888)
