### ISSUE TITLE
Render: ResetTransform() breaks scaling

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1416]
## Tasks

Re-apply scaling after `ResetTransform()` is called in [these files](https://github.com/ScottPlot/ScottPlot/search?q=resettransform):

- [x] src/ScottPlot/Renderable/AxisTicksRender.cs
- [x] src/ScottPlot/Renderable/AxisLabel.cs
- [x] src/ScottPlot/Plottable/Text.cs
- [x] src/ScottPlot/Plottable/Image.cs
- [x] src/ScottPlot/Plottable/RadialGauge.cs

## Issue Description

_This report came in from Andreas via email regarding ScottPlot Version: 4.1.27 (latest):_

Rendering Bitmaps for the printer from line charts via `formsPlot1.Render(1200,800,false,2)` not all elements are taking the scaling factor 2 as shown here:

![image](https://user-images.githubusercontent.com/4165489/139612519-2e6ba10b-2ec0-4f39-a89e-bb643d96b3d7.png)

I found out in AxisTicksRender.cs the line `gfx.ResetTransform()` is killing the scaling factor also!

When saving actual factor(s) first and scaling anew after ResetTransform it works fine and TickLabels are still rotated:

![image](https://user-images.githubusercontent.com/4165489/139612529-061cbd3b-26b1-4568-9a3e-4f1f0256d618.png)

The same applies for the RadialGauge as well as for the shifting of the texts for those:

![image](https://user-images.githubusercontent.com/4165489/139612540-632aa9b7-8000-48b5-a95f-63ad1c24e4c5.png)

![image](https://user-images.githubusercontent.com/4165489/139612545-bdbce024-d049-4eeb-8781-9c596bb70ba0.png)

I think `ResetTransform()` is also applied for single images and single text (rotation) where might be solved the same way.
Would be happy if this is of help.

## Proposed Fix

Andreas emailed-in some source code with the fix applied: [2021-10-13.zip](https://github.com/ScottPlot/ScottPlot/files/7450378/2021-10-13.zip)

![image](https://user-images.githubusercontent.com/4165489/139613468-4fb36b7a-2dd0-46f0-83d0-c3722d02cb1f.png)

![image](https://user-images.githubusercontent.com/4165489/139613498-2ddce04e-b97e-4a72-94f4-aed52aba5fa4.png)

Yes I'm using GitHub Desktop 😅

**Comment by swharden** [comment]
I'm reminded that it's _critically_ important that code does not `Graphics.FromImage()` directly but instead uses this helper function which applies scaling. 

Anyone who calls `ResetTransform()` must manually re-apply this scale. Perhaps a helper function could be used to prevent accidental resetting.

https://github.com/ScottPlot/ScottPlot/blob/fff2eacc93d33153b591e26daf4ed5169d6a4544/src/ScottPlot/Drawing/GDI.cs#L88-L95

**Comment by AndXaf** [comment]
Hey Scott,

this seems only to be a problem when there is more than one time drawn onto the Graphics object before it is disposed - like AxisTicks, AxisLabels and the RadialGauge.
Since Text is only drawn one time it does not appear as problem.
Probably for Image it is also not an issue.
