### ISSUE TITLE
🗺️ ScottPlot 5 Release Roadmap

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2984]
This issue tracks goals and progress for the last several weeks of 2023

### Highest Priority: Release ScottPlot 5
* ScottPlot 5 release target is **January 1, 2024** 🚀
* ScottPlot 5 has been available as a preview package since January 1, 2023
* Several critical features will be prioritized before the release, marked with the https://github.com/ScottPlot/ScottPlot/labels/SP5%E2%9C%A8 label
* The cookbook must be significantly extended (including an improved website)
* All ScottPlot.net webpages must be updated to reflect the ScottPlot 5 API
* A WinForms demo app will be created to demonstrate control-specific functionality
* Standalone demo apps will be created for all major targets
* ScottPlot 4 issues to resolved after ScottPlot 5 is released will be marked with the https://github.com/ScottPlot/ScottPlot/labels/SP4%20%E2%8C%9B label

### Scott's Agenda (Updated Dec 11, 2023)
- [x] #2945
- [x] #2944
- [x] #2941
- [x] #3007
- [x] #3009
- [x] #2950
- [x] #3014
- [x] #2943 
- [x] #3027 
- [x] #3026
- [x] #3009
- [x] #2939
- [x] resolve most open issues
- [x] 📦 publish updated NuGet packages (Dec 3)
- [x] #3079 
- [x] #3080
- [x] #2755 
- [x] Improve ScottPlot 5 Cookbook HTML/JS generation
- [x] close as many small open issues as possible
- [x] #2962
- [ ] Close all https://github.com/ScottPlot/ScottPlot/labels/SP4%20%E2%8C%9B issues oldest to newest
- [ ] Close all remaining issues oldest to newest
- [ ] 📦 publish updated NuGet packages
- [ ] Translate as many ScottPlot 4 cookbook recipes into ScottPlot 5 as possible
- [ ] 📦 publish updated NuGet packages
- [ ] Resolve all ScottPlot 5 TODOs on https://scottplot.net/metrics/ and in TODO.cs
- [ ] Resolve all ScottPlot 4 TODOs https://scottplot.net/metrics/

**Comment by swharden** [comment]
I've got a lot of good momentum currently. I'm going to close this and stop tracking progress here. Still on target for Jan 1, 2024 release
