### ISSUE TITLE
Improve finance demo

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4483]
This issue tracks short term goals to improve financial charting resulting from a discussion today with @quantfreedom and @VladislavPustovarov

* Progress will be evaluated using the [Sandbox.WinFormsFinance](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.WinFormsFinance) project

* This work extends #4385

## Task 1: Scott
- [x] Improve cursor tracking (show labels, snap to bars, etc.)
- [x] Improve performance for very large numbers of bars (50,000)
- [x] Simplify the process of automatic vertical scaling. ~~Use strategy pattern to allow multiple scaling strategies including custom ones injected by the user.~~ _It is already a function that can be created by the user and assigned to the `ContinuousAutoscaleAction` action so creating additional classes is not required._
- [x] Add something like "GetOhlcNearest(x)" to simplify mouse snapping
- [x] Improve tick behavior when windows are resized. Mimic TradingView.com where ticks "slide" off the screen to the left but do not change in density as the window is resized

## Task 2: Vlad
- [x] Add more views by creating classes in the [TickGenerators/Financial](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5/TickGenerators/Financial) namespace (suggested views are listed below)
- [x] Improve the logic used to decide which view is best given the figure size and axis limits

```
YearOnly - Year
YearAndJuly - Year, July
YearAnd2Months - Year, May, Sep
YearAnd3Months - Year, Apr, Jul, Oct
YearAnd4Months - Year, Mar, May, Jul, Sep, Nov
Months - Year, then each month
MonthAndThirdMonday - months are short names, days are the number
MonthAndEveryMonday - months are short names, days are the number
MonthAndEveryOtherDay - months are short names, days are the number
MonthAndEveryDay - months are short names, days are the number
DayAndEvery12Hours - show the day number for midnight, then show 6, 12, 18
DayAndEvery4Hours
DayAndEvery3Hours
EveryHour
EveryHalfHour
Every15Minutes
Every5Minutes
EveryMinute
Seconds45
Seconds30
Seconds15
Seconds10
Seconds5
Seconds1
```

## Task 3: Scott
_This work will be performed after Vlad finishes the date work above_
- [ ] Add lower limit to ensure ticks don't get smaller than candles
- [x] Add volume bars to the demo
- [x] Add additional "subplots" showing technical indicators to the demo
- [ ] Refine pan/zoom so candles aren't cut in half horizontally
- [ ] Improve support for charts that have candles of different widths
- [ ] Add grid feature as shown in [this comment](https://github.com/ScottPlot/ScottPlot/issues/4385#issuecomment-2439643858)

**Comment by swharden** [comment]
@quantfreedom and @VladislavPustovarov - got it, thanks!

**Comment by swharden** [comment]
I added cursor tracking with highlighted labels and candle snapping in the horizontal axis

I'll keep working in #4484

![snap2](https://github.com/user-attachments/assets/d44078c0-3abc-4e0e-90b8-44606b2e0c83)

**Comment by quantfreedom** [comment]
![tenor](https://github.com/user-attachments/assets/1135ad09-fbfe-4c2f-8e5f-cb685505ec3f)
holy jesus ... this thing is looking so damn sexy ... this is beyond nuts that all of this is even happening ... insane

**Comment by swharden** [comment]
@VladislavPustovarov I have an important message about performance.

Performance is indeed very bad when displaying 50,000 candles. However, I think this should never be done. Showing so many distinct candles on a 800px wide chart means each candle is less than 0.02 pixels wide.

I highly recommend detecting when you are trying to display an extremely large number of candles and re-binning the data so that candles are at least 1 pixel wide or wider. I don't think a user will ever want to see second-width candles on a years-wide plot. 

For example, TradingView limits how far you can zoom in or out based on the width of candles. This prevents more than a few thousand candles from ever being seen at one time. Users who want to see more time can increase the candle width.

If you implement this strategy in your application, it will be extremely performant. Also, no modification to ScottPlot is required to achieve this high performance.

Let me know if you have any questions about this topic! I updated the demo app to show render time and frame rate at the top in the title area. It's interesting to see how poor performance gets when candles are significantly smaller than 1 pixel wide.

![candlePerf2](https://github.com/user-attachments/assets/edf48125-9c82-443d-b63d-978332e1fdc4)

**Comment by swharden** [comment]
## Resizing Behavior

I'm writing this down to put words to the behavior that needs to change.

Presently, resizing the window "squeezes" the plot so there is no change in axis limits.
For financial charting, this is _not_ the desired behavior.
![resize1](https://github.com/user-attachments/assets/699cfa90-8657-4d6d-9d37-0a3d69bcf57f)

The chart should respond to resize events by "sliding" data off the screen to the left to achieve a fixed "distance per pixel" ratio through resize events
![resize2](https://github.com/user-attachments/assets/2284ff28-4dc2-4955-8918-358f3a8523bb)

**Comment by swharden** [comment]
I figured out a way to implement this behavior using a custom axis rule

This completes my list of tasks so I'm going to merge #4484 and ***we can pick up the discussion again after you make progress on improving the data tick logic*** Feel free to reach out in the meantime if you have any questions 👍

![resize3](https://github.com/user-attachments/assets/48119496-c90b-4d16-9ca2-8862cfd0a3b5)

**Comment by quantfreedom** [comment]
having some issues with the candle width remaining stable as you zoom in and out

as you stay in one place and zoom out and zoom in each time the candle width gets smaller and smaller even though we are just zooming back and forth. 

This causes a problem with being able to properly set the display on the x axis based on candle width

![Sandbox WinFormsFinance_k2ByYdsu1C](https://github.com/user-attachments/assets/ab38ea2e-73fd-469f-b603-b2175bbf0668)


Also when you zoom in and out ... lets say you zoom out and the x axis changes ... it seems like you have to zoom in 3 times for it to change to the next level then you have to zoom out 3 more times for it to change but i am guessing it should always just be one zoom to change from one level to the next

![QuantFreedom Av Plotting_aMcmcccmZ3](https://github.com/user-attachments/assets/3efb36b3-a6e9-4433-b4e2-16a20cb21944)

@VladislavPustovarov can you comment on this so that you can get updates

**Comment by quantfreedom** [comment]
also the candle width seems to be getting smaller and smaller as you zoom in and out in one place
![QuantFreedom Av Plotting_LzyZP59XEs](https://github.com/user-attachments/assets/65718bd9-386f-4b63-9985-fd51ac937fc0)

```c Sharp
public virtual void Render(RenderPack rp)
    {
        if (DateTimes.Length == 0)
            return;

        // allow drawing outside the data area
        rp.CanvasState.DisableClipping();

        // get the best tick generator given the field of view
        int minIndexInView = (int)(Math.Max(0, Axes.XAxis.Range.Min));
        int maxIndexInView = (int)(Math.Min(DateTimes.Length - 1, Axes.XAxis.Range.Max));
        if (maxIndexInView <= minIndexInView) return;
        TimeSpan timeSpanInView = DateTimes[maxIndexInView] - DateTimes[minIndexInView];
        IFinancialTickGenerator tickGenerator = GetBestTickGenerator(timeSpanInView, rp.DataRect.Width);
        List<(int, string)> ticks = tickGenerator.GetTicks(DateTimes, minIndexInView, maxIndexInView);

        widthOfCandleInPixels = rp.DataRect.Width / Axes.XAxis.Range.Span;
        // render each tick label
        using SKPaint paint = new();
        foreach ((int x, string label) in ticks)
        {
            Pixel px = new(Axes.XAxis.GetPixel(x, rp.DataRect), rp.DataRect.Bottom);
            LabelStyle.Render(rp.Canvas, px, paint, label);
        }
    }

    private IFinancialTickGenerator GetBestTickGenerator(TimeSpan timeSpan, float widthInPixels)
    {
        // adjust the scale so small plots show fewer ticks
        double scaledViewDays = timeSpan.TotalDays * 600 / widthInPixels;
        var maxWidth = LabelStyle.Measure(labelFormat).Size.Width;

        Trace.WriteLine(widthOfCandleInPixels);
        Trace.WriteLine(maxWidth);
        Trace.WriteLine(maxWidth / widthOfCandleInPixels);
        Trace.WriteLine("");

        var numCandles = maxWidth / widthOfCandleInPixels;

        if (widthOfCandleInPixels > 85)
        {
            return new EachCandleValue();
        }
        else if (widthOfCandleInPixels > 40)
        {
            return new EveryOtherCandle();
        }
        else if (widthOfCandleInPixels > 20)
        {
            return new EveryFourthCandle();
        }
        else if (scaledViewDays < 180)
        {
            return new MonthsAndMondays();
        }
        else if (scaledViewDays < 360 * 2)
        {
            return new Months();
        }
        else
        {
            return new Years();
        }
    }
```

**Comment by tiger2014** [comment]
@swharden 

Thank you for providing such high-quality charting solutions for the C# community.

As a financial hobbyist, I often need to plot candlestick charts with volume and add indicators like EMA, RSI, and others. Let me outline the common requirements for financial charting:

1. The typical financial candlestick format includes: time, open, high, low, close, and volume.
2. Since financial charts have non-continuous time intervals, it would be ideal to handle non-continuous time automatically without requiring manual adjustments. If the data includes volume, the chart should automatically generate volume bars without extra steps. For example, a single line like Plot.Add.Candlestick(candles) could generate a candlestick chart with volume.

![image](https://github.com/user-attachments/assets/5de29832-9c20-4403-83eb-ba0ae10194fb)

3. Convenient support for adding subplots, as indicators like RSI are often displayed in subplots.

![image](https://github.com/user-attachments/assets/16bda84a-d17e-414b-ab7b-f5a6039806c4)

4. Most indicators are lines, so a simple way to plot lines would be highly valuable.

**Comment by swharden** [comment]
Hi @tiger2014, thank you for your feedback! I can see we have a growing collection of developers who are interested in seeing ScottPlot improve support for financial charts, and I'm excited to keep working to make it better!

Part of my effort is directed at adding these new features, and part of my effort is also supporting others as they contribute new features, and also to provide some direction about which features to work on in which order. Right now we are focused on adding better support for dates and times (the content of the discussion above), and I probably will wait until that contribution is submitted before putting more of my direct effort into improving financial charting, but it is a goal of mine for sure.

Based on your feedback, in my next iteration of the financial demo I'll add volume bars and also separate plots like you show to show SMA, RSI, and other similar indicators. Thanks for this suggestion!

**Comment by swharden** [comment]
> Based on your feedback, in my next iteration of the financial demo I'll add volume bars and also separate plots like you show to show SMA, RSI, and other similar indicators. Thanks for this suggestion!

I modified the "to-do" list at the top of this issue to add my work after Vlad's. I'll re-open this issue and use it to track the progress Vlad is making toward improved support for date axis labels.

**Comment by swharden** [comment]
Hi @quantfreedom and @VladislavPustovarov, I wanted to ping you two to see how things are going. If you find you're having more trouble than expected, let me know and we can either hop on a call to take a look together or I can take these tasks off your plate, I'll do them some day soon, we we can decide if/how you may want to contribute to other features in the future. 

I don't want this to become a bottleneck on your end! Let me know what I can do that you would find most helpful.

Scott

**Comment by quantfreedom** [comment]
@swharden hey man I was literally going to reach out as well and give you an update soon. But for the most part we are still working on building out the framework to our application right now 

On my end I'm almost done setting up all of the different windows that I need and then from that point it's just going to be becoming a Scott plot expert

Right now I'm building a tpo chart and volume profile chart that I will send u a video about soon

But how are things on ur end

**Comment by VladislavPustovarov** [comment]
Hey, @swharden I'm trying to find a way how to optimize chart, it starts freezing when I'm zooming in 
![image](https://github.com/user-attachments/assets/cfd04385-15e4-4fbe-88a2-dab9f35bea70)

**Comment by swharden** [comment]
> find a way how to optimize chart

I can help with that for sure! But I prefer to focus on one thing at a time according to the roadmap outlined above - if I don't stay rigidly focused I tend to get pulled 100 different directions and don't make good progress on anything 🤪

I'm _definitely_ willing to help with that, but let's clear out the present task list before I dive in to what may be a 🐰 🕳️

**Comment by VladislavPustovarov** [comment]
Oh, yeah sorry, we already made some progres with FinancialDateTime bar, I plan to do all from check list by Sunday

**Comment by VladislavPustovarov** [comment]
@swharden https://imgur.com/64Ag7yW

**Comment by swharden** [comment]
![vald](https://github.com/user-attachments/assets/a8c6a1d4-adfa-4826-b1fe-201c7d1f5d5e)

**Comment by quantfreedom** [comment]
program.cs
```
using ConsoleApp1;
using ScottPlot;

Plot plot = new();

// create sample data
double[,] data = new double[10, 10];
for (int x = 0; x < data.GetLength(1); x++)
{
    for (int y = 0; y < data.GetLength(0); y++)
    {
        data[y, x] = Math.Sin((x * y) / 20.0) * 100;
    }
}
double[,] data2 = ScottPlot.SampleData.MonaLisa();


// create a TPO plot loaded with our data
TpoPlot tpo = new(data2);

// add the TPO plot to the graph
plot.Add.Plottable(tpo);

ScottPlot.WinForms.FormsPlotViewer.Launch(plot);
```
consolueapp1
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ScottPlot.WinForms" Version="5.0.46" />
	</ItemGroup>

</Project>
```

tpoplot.cs
```
using ScottPlot;

namespace ConsoleApp1;

public class TpoPlot:IPlottable
{
    public bool IsVisible { get; set; } = true;
    public IAxes Axes { get; set; } = new Axes();
    public IEnumerable<LegendItem> LegendItems => LegendItem.None;
    public AxisLimits GetAxisLimits() => AxisLimits.NoLimits;
    public IColormap Colormap { get; set; } = new ScottPlot.Colormaps.Turbo();

    LabelStyle LabelStyle { get; set; } = new()
    {
        Alignment = Alignment.MiddleCenter,
        IsVisible = true,
    };

    public double[,] Data { get; }

    public TpoPlot(double[,] data)
    {
        Data = data;
    }


    public void Render(RenderPack rp)
    {
        for (int x = 0; x < Data.GetLength(1); x++)
        {
            for (int y = 0; y < Data.GetLength(0); y++)
            {
                double value = Data[y, x];
                if (double.IsNaN(value))
                    continue;
                string label = Convert.ToChar(x + (byte)'A').ToString();
                ScottPlot.Color color = Colormap.GetColor(value / 100);
                DrawCell(rp, x, y, value, label, color);
            }
        }
    }

    void DrawCell(RenderPack rp, int x, int y, double value, string label, ScottPlot.Color color)
    {
        CoordinateRect cell = new(x, x + 1, y, y + 1);
        PixelRect cellRect = Axes.GetPixelRect(cell);

        // background color
        Drawing.FillRectangle(rp.Canvas, cellRect, color);

        // render text only if the cells are lagre enough
        if (cellRect.Width > 10)
            LabelStyle.Render(rp.Canvas, cellRect.Center, rp.Paint, label);
    }
}
```

**Comment by swharden** [comment]
Hi @VladislavPustovarov and @quantfreedom,

I merged #4551 but because of the reasons discussed in https://github.com/ScottPlot/ScottPlot/pull/4551#issuecomment-2496174410 (mostly point 2) I'm inclined to not consider task 2 above complete. I think I would prefer to wait before I invest my time into task 3 until task 2 is more effectively resolved. I welcome feedback (including if I'm misunderstanding whether or not the present behavior is the intended behavior), but as I see it the horizontal axis tick labels do not closely mimic those of TradingView.

While the `EveryNthUnit` is helpful, I still think each of the ~25 time scales listed in "task 2" at the top of this page requires its own logic/class to achieve tick labels similar to TradingView. I'm not attached to my implementation recommendation (if you can do it all in one class or using a different architecture, that's fine), but I'd like to see this demonstrate better functionality before proceeding to the other tasks outlined above.

Let me know if you have any questions! I'm happy to hop on a call if it's easier too.

**Comment by swharden** [comment]
Adding additional context, here are a few different time scales and the expected tick labels:

## Years
![image](https://github.com/user-attachments/assets/1b883581-ac9e-423f-b6ea-32b129886a96)

## Years and Some Months
![image](https://github.com/user-attachments/assets/9deeb6fd-eb35-4486-a7fe-b31c64f915bd)

## Months and Some Mondays
![image](https://github.com/user-attachments/assets/6440c3d3-2c8d-456a-9838-35f203833c5a)

## Every Other Day
![image](https://github.com/user-attachments/assets/b67c261a-1b31-48ba-b175-690c066c0c00)

## Days and HalfDays
![image](https://github.com/user-attachments/assets/2396b30e-62c8-424e-8bc2-bae0e11244d3)

## Every Fifteen Minutes
![image](https://github.com/user-attachments/assets/8dffc748-409b-45bb-8629-cd01a3318590)

## Every Five Minutes
![image](https://github.com/user-attachments/assets/8a24d1e0-c07c-4123-9b1a-73b043554031)

**Comment by VladislavPustovarov** [comment]
@swharden hi, can we shcedule a call realted to this topic, I want to discuss some moments

**Comment by swharden** [comment]
![image](https://github.com/user-attachments/assets/d47e184e-588d-4aaa-8815-dd85f36ffdb2)

**Comment by swharden** [comment]
![image](https://github.com/user-attachments/assets/91f1b677-761b-46f6-a2a8-b51c3416ed34)

**Comment by swharden** [comment]
Short term goals: 

1: demonstrate how to have stacked plots which share an X axis

2: start creating a plottable that displays data in a grid as shown in the screenshot

![image](https://github.com/user-attachments/assets/33d65fd8-2d8e-47e6-8a8d-be04b6270fcb)

**Comment by swharden** [comment]
Following-up, I'm tracking the "stacked chart" issue in #4600 now.

It's turning out to be a lot more complex than I initially expected, but I'm very motivated to find a solution. I'm temporarily elevating that issue above all others until a solution is reached...

**Comment by tiger2014** [comment]
> Hi [@tiger2014](https://github.com/tiger2014), thank you for your feedback! I can see we have a growing collection of developers who are interested in seeing ScottPlot improve support for financial charts, and I'm excited to keep working to make it better!
> 
> Part of my effort is directed at adding these new features, and part of my effort is also supporting others as they contribute new features, and also to provide some direction about which features to work on in which order. Right now we are focused on adding better support for dates and times (the content of the discussion above), and I probably will wait until that contribution is submitted before putting more of my direct effort into improving financial charting, but it is a goal of mine for sure.
> 
> Based on your feedback, in my next iteration of the financial demo I'll add volume bars and also separate plots like you show to show SMA, RSI, and other similar indicators. Thanks for this suggestion!

Hi @swharden, has there been any progress on the proposal to easily plot candles and volume?

**Comment by swharden** [comment]
Hi @tiger2014, yes! I think the demo app has an advanced finance demo that demonstrates this (screenshot and link below)

This issue got pretty big and the primary stakeholders have moved the conversation to Discord and Zoom so I'll close this issue but improving financial charting is still very much a high development priority at ScottPlot 🚀 

---

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/MultiplotCollapsed.cs

![Image](https://github.com/user-attachments/assets/b140986a-d195-407a-93e6-9b2d8cdca176)

![Image](https://github.com/user-attachments/assets/435d8335-7420-44ba-8cc8-6b8f1590b169)
