### ISSUE TITLE
Multiplot: add mouse interactivity

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4600]
This issue tracks progress toward adding mouse-interactive functionality to the `Multiplot` feature which was quietly added in ScottPlot 5.0.40 (Oct 16, 2024) and previously was only supported in console applications. This work was prioritized in an effort to make progress toward improving financial charting capabilities (#4483)

## Roadmap

- [x] Extend `Multiplot` to support rending onto an existing surface (#4628)
- [x] Add `Multiplot` to `IPlotControl` (#4628)
- [x] Remove `Interaction` property and related code (#4630, 889b4acfdc3c6f6ee1fa16da110a77effb21e438)
- [x] Remove `Plot.PlotControl` property (#4631)
- [x] Update all `UserInputProcessor` and `Interactivity` code to act at the `Multiplot` level (#4632)
- [x] Add advanced subplot positioning features to `Multiplot` (#4633)
- [x] Add multi-plot shared axis features to `Multiplot` to help syncing axis limits across subplots (#4635)
- [x] Add multi-plot alignment features to `Multiplot` to help sync layouts across subplots (#4637)
- [x] Showcase new features in the demo application (#4638, #4639, #4640)
- [x] Update website documentation
  * https://scottplot.net/faq/multiplot/
  * https://scottplot.net/faq/shared-axes/
  * https://scottplot.net/faq/shared-layout/
  * https://scottplot.net/demo/5.0/#shared-axes
  * https://scottplot.net/demo/5.0/#multiplot-with-shared-axes
  * https://scottplot.net/demo/5.0/#synchronizing-axes-across-multiple-plot-controls

<details>

## Goal

It should be easier to create plots like this which have multiple _stacked_ Y axes and a shared X axis.

![image](https://github.com/user-attachments/assets/0ebd415e-d621-45fc-a645-ff7d47b0c4fb)

## Option 1: ~Refactor the Layout System~

<details>

## Current Layout System

The `Render()` method calls `Plot.LayoutManager.LayoutEngine.GetLayout()` which returns a `Layout` which has `Size` (thickness) and `Offset` (distance from the data area) for each

Users can create their own layout engine that implements `ILayoutEngine` and replace the default one to customize layouts for complex multi-axis plots

However, since `Layout` currently only holds size and offset for each panel (not an actual pixel rectangle), full customization cannot be achieved. The present system was designed assuming all layouts are aligned with a single rectangular data area, but for users wishing to create stacked plots (e.g., financial charts that display price on an upper axis and RSI on a lower axis, #4483) this is not the case and the existing layout system cannot lay-out these types of plots

## Proposed Solution

Refactor the `Layout` object and remove these properties:
```cs
public readonly Dictionary<IPanel, float> PanelOffsets { get; }
public readonly Dictionary<IPanel, float> PanelSizes { get; }
```

and replace them with something like:
```cs
public readonly Dictionary<IPanel, PixelRect> PanelRectangles { get; }
```

## Potential Challenges

* **Mouse Interaction Issues:** Click-dragging vertically should probably be disabled, otherwise it could cause some very weird behavior... or we have to figure out which axis was clicked and only drag that axis. This is doable, but will be a lot of work (refactoring the mouse hit detection and dragging system) so it should be challenged in a different issue/PR

* **Multiple Data Area Issues:** Supporting stacked axis layouts like this may pose new serious issues because fundamentally this means plots have more than one "DataArea", so clipping may be a serious issue. Similarly, the "frame" around plots won't be drawn by default since frame lines around standard plots are drawn by each of the 4 standard axes.

</details>

## Option 2: Improve interactive support for `Multiplot`

Extend the `Multiplot` which was recently added but does not (yet?) support mouse interactivity. https://scottplot.net/cookbook/5.0/MultiplotRecipes/

</details>

**Comment by swharden** [comment]
The implementation strategy I'm learning toward is as follows:

* Extend the existing [MultiPlot functionality](https://scottplot.net/cookbook/5.0/MultiplotRecipes/) by making it mouse interactive
* Add a `MultiPlot` property to user controls 
  * The default state is that the `MultiPlot` contains a single `Plot` named `Plot` for backward compatibility
  * Users can `formsPlot1.MultiPlot.AddSubplot()` to add additional panels
* The entire user input processor must be refactored to support `MultiPlot` instead of `Plot` (a very large amount of work)

**Comment by swharden** [comment]
There's a lot to do to improve mouse interaction support, but this wasn't too bad to get off the ground...

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // the Plot is actually the single Plot inside a Multiplot
        formsPlot1.Plot.Add.Signal(Generate.Sin());

        // subplots can be created and added to the plot
        var plot2 = formsPlot1.Multiplot.AddPlot();
        plot2.Add.Signal(Generate.Cos());
    }
}
```

![subplot](https://github.com/user-attachments/assets/21f17211-6abb-4fd5-b1f3-bc2537ed1729)

**Comment by swharden** [comment]
This is going _really_ well. This feature may be achieved in a few days instead of a few weeks. As of #4632, **a single control may now be used to display multiple interactive plots.** This should allow for easier implementation of plots with shared axes and shared layouts because we no longer have to sync settings across multiple plot controls.

```cs
// work with the plot like normal
formsPlot1.Plot.Add.Signal(Generate.Sin());

// add a sub-plot and interact with it
var plot2 = formsPlot1.Multiplot.AddPlot();
plot2.Add.Signal(Generate.Cos());
```

![multiplot2](https://github.com/user-attachments/assets/d637f4be-e036-4422-bf9b-a66dac857149)

**Comment by swharden** [comment]
Hi @quantfreedom and @VladislavPustovarov, I want to draw your attention to recent merges which have added multiplot functionality to the main branch of this repository. It's not pushed to NuGet yet, but it is now developed enough that you may experiment with it and let me know if you recommend any API changes.

Specifically, check out the custom multi-plot demo recently added to the WinForms demo application:

https://github.com/ScottPlot/ScottPlot/blob/16728cb48659e67e67d09aa967cf9beba6edf04b/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/MultiplotCollapsed.cs#L12-L75

![sharedfinance](https://github.com/user-attachments/assets/a98ce719-414c-4ade-bbb5-44a5a0ffc895)

**Comment by quantfreedom** [comment]
@swharden looks great ... is there any way in this demo that you could put the time statistics grid at the bottom and on the y-axis for the time statistics it wouldn't be numbers it would be labels

Is that something that we should be able to do or know how to do because I think at the core of us needing the separation is that time statistics grid

But if that's something that we should be able to do then I'll be happy to figure that out

**Comment by swharden** [comment]
Hi @quantfreedom,

To achieve an effect similar to the one in your screenshot, setup a `Multiplot` with two `Plot` objects we'll call `plotPrice` and `plotGrid`. To set Y axis labels for `plotGrid` you can use the strategy here described on https://scottplot.net/cookbook/5.0/CustomizingTicks/SetTicks/ and it should get you were you want to go! 🚀 

There may be some nuance around using right ticks instead of the standard ones... I'll explore that and ensure multiplot properly supports plots using nonstandard axes.

**Comment by swharden** [comment]
> There may be some nuance around using right ticks instead of the standard ones...

Wasn't hard, but I'll update the demo to showcase this style

![image](https://github.com/user-attachments/assets/5a327f1f-9207-476a-88e4-16d0bed9dc45)

**Comment by TradeForgeFR** [comment]
This feature is amazing, I will try to create the same, but vertically as Overchart does
![image](https://github.com/user-attachments/assets/77d0369b-d46a-45be-9349-313c034e8dcb)

**Comment by swharden** [comment]
Based on your suggestion I added a demo application showcasing multiplot controls with resizable subplots:

![multiplot-resize](https://github.com/user-attachments/assets/9e8a48dd-4232-4562-a206-9854639e2120)

https://github.com/ScottPlot/ScottPlot/blob/e650e7b5ff89c1ba547191866980c6be72f01016/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/MultiplotCollapsed.cs#L1-L221
