### ISSUE TITLE
Triaged Tasks and Features (Dec 2020)

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#651]
**This page is a collection of low-priority tasks and features** I hope to accomplish eventually, but are not the primary focus of my development efforts at this time. This list originated from #412

### General
- [ ] Refactor markers ([#386](https://github.com/swharden/ScottPlot/pull/386)) to be classes instead of defined in an enum. Markers will implement `IMarker`, live in `ScottPlot.Markers`, markers have the ability to draw themselves. This makes it easy to switch between markers and even create custom markers that work for all plot types without modifying any ScottPlot code.
- [ ] Turn `Tools` static class into a `Tools` namespace with smaller static classes
- [x] Make it easier to reset the plot by creating `Plot.Reset()` (#407)
- [ ] Option for non-overlapping manual tick labels (#648, #644)
- [ ] Support for image as axis label (with demo) (#446, #696)

### Plottable-Specific
- [x] heatmaps (#420, #441, #458, #424, #482, #457) need refinement and better cookbook examples
- [x] vector fields (#438, #439) need refinement and better cookbook examples
- [ ] Add options to customize location of L-shaped scale bar (#363)
- [ ] Add minRenderIndex and maxRenderIndex to scatter plots (#566)
- [ ] Extend the legend to support horizontal orientation or columns (#580)
- [ ] OHLC bars should show values in a tooltip when the mouse is near them (#696). When this is added it seems useful to make a static class with static methods for drawing tooltips, and it can simply be called from any plottable which needs a tooltip drawn.

### Control-Specific
- [x] Add a right-click menu to WpfPlot (like FormsPlot's)
- [ ] Improve WPF Performance with BitmapSource (#522)
- [ ] Add print and print preview to user control right click menus (#524)
- [x] Use delegate and/or timer to automatically render after plottables are added (#525, #637)
- [x] Use a `Configuration` class (not a `Configure()` method) to customize control settings (#547, #637)

### Documentation
- [ ] Create a Finance Demo (not a cookbook example, but a full demo program) to consolidate common finance-related tasks in one program. This demo should describe how to add live incoming data (#395, #403, #637)
- [ ] figure out how to implement better shared axes in user controls (#399, #429)
- [ ] add "view source code" button to all demos (#434)
- [ ] create MVVM control demo (#633)

**Comment by swharden** [comment]
I made a new list of triaged tasks/goals (#716) and am closing this one
