### ISSUE TITLE
Triaged Tasks and Features (Feb 2021)

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#716]
**This page is a collection of tasks and features I want to focus on.** I hope to accomplish everything eventually, but I will arrange this list according to what I think the primary focus of my development efforts should be. This list carries over from #651 and #412.

## Immediate Priority

**⚠️ My highest priority at this time is releasing ScottPlot 4.1** and I will try to minimize effort devoted to new features while I work to complete these tasks:

- [x] Fix warnings due to tests and demos referencing the old API (#718)
- [x] Create a repo for the website #714 [ScottPlot/Website](https://github.com/ScottPlot/Website)
- [x] Create NuGet organization https://www.nuget.org/profiles/ScottPlot
- [x] Implement pixel-aware highlightable plot with demo (#709, #722)
- [x] Add auto-generated API documentation to cookbook (#726, #727)
- [x] Require every Plot method and parameter to have XML documentation (#738)
- [x] Require every Plottable to have an XML summary (#738) 
- [x] Add Plot and Plottable API information to cookbook (#738) 
- [x] Refactor the cookbook to add API documentation support. (#727, #738, #756)
- [x] Improve website documentation: Quickstarts
- [x] Improve website documentation: FAQ (https://github.com/ScottPlot/Website/issues/6)
- [x] Implement render queue #736, #761, #813
- [x] Refactor bar plots #842
- [x] Improve DateTime tick density calculations (#725, #925, #828)
- [ ] Create a modern demo/cookbook for ScottPlot 4.1 👈⚠️ ***WORKING ON THIS NOW***
- [ ] Improve website documentation to better document user controls (#887)
- [x] Add "open in new window" to right-click menu (#958)
- [ ] ✨🚀  Remove the beta/pre-release designation and release ScottPlot 4.1 on NuGet (#715)
- [ ] Release a 4.0 package with a pop-up readme informing people about 4.1 (#949)
- [ ] Review GitHub Issue templates to ensure they're up to date (#966)

## High Priority
- [ ] Improve async rendering support and documentation/demonstration of the render queue (#736, #761, #813)
- [ ] Add methods to make it easier to add live data to scatter, signal, bar, and finance plots. This may or may not involve a data object to manage array resizing and data validation. (#815, #841, #827)
- [ ] Improve API consistency for deep styling options (#981)

## Moderate Priority
- [ ] Use nullable annotations #691
- [ ] Improve the heatmap plot type [project 1](https://github.com/orgs/ScottPlot/projects/1), #666, #667, #701, #707, #713
- [ ] Clean the `/dev` folder and move meta content to the ScottPlot website
- [x] Add more FAQ pages (https://github.com/ScottPlot/Website/issues/6)
- [ ] Refactor TickCollection module to improve support for advanced tick features (#725, #925, #926, #475, #469, #935)
- [ ] Prevent obsolete plot methods from being browsable (#963)
- [ ] Document how to create custom plot types on the FAQ page (#973)

### General
- [ ] Refactor markers ([#386](https://github.com/swharden/ScottPlot/pull/386)) to be classes instead of defined in an enum. Markers will implement `IMarker`, live in `ScottPlot.Markers`, markers have the ability to draw themselves. This makes it easy to switch between markers and even create custom markers that work for all plot types without modifying any ScottPlot code. Create a `MarkerSeries` plot type that lets individual markers be customized (#784, #785)
- [ ] Break the `Tools` class into smaller classes. Move statistical logic out of histogram class and improve names and documentation in the histogram class. (#930, #932, #934, #624)
- [ ] Create a `Generate` class with functions with more logical and better documented function signatures than `DataGen` (#902, #903)
- [ ] Option for non-overlapping manual tick labels (#648, #644)
- [x] Support for image as axis label (#446, #696)
- [ ] Create architecture.md
- [ ] Markers should be classes implementing `IMarker` allowing custom markers (#786)

### Plottable
- [ ] Add options to customize location of L-shaped scale bar (#363)
- [x] Add minRenderIndex and maxRenderIndex to scatter plots (#566)
- [ ] Extend the legend to support horizontal orientation or columns (#580)
- [ ] OHLC bars should show values in a tooltip when the mouse is near them (#696). When this is added it seems useful to make a static class with static methods for drawing tooltips, and it can simply be called from any plottable which needs a tooltip drawn.
- [ ] Improve efficiency of scatter plot point distance measurements (#709)

### Controls
- [ ] Add print and print preview to user control right click menus (#524)
- [ ] Allow the user to define custom left-click behavior (#739)
- [ ] Is click-drag-rectangle multi-point-select possible? If so, make a demo (#855)
- [ ] Add more error checking and tests to the Control module (#940)

### Documentation
- [ ] Create a Finance Demo (not a cookbook example, but a full demo program) to consolidate common finance-related tasks in one program. This demo should describe how to add live incoming data (#395, #403, #637)
- [ ] Work toward enabling [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) at the project level

**Comment by swharden** [comment]
This list was re-evaluated in May 2021 and is continued in #1028
