### ISSUE TITLE
Improve Cookbook/API Website

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#752]
### Goal
* I am working toward adding more documentation (like a FAQ section) to the ScottPlot website
* I want people who find the Cookbook from Google to know these other documentation pages exist
* ~~I am considering making the cookbook pages visually distinct from the website in an effort to make it obvious that more documentation exists outside the cookbook~~ 
  * I'm doubling efforts to make the cookbook pages integrate fully with the existing website. 
  * This rules-out a totally static (and therefore standalone) cookbook. 
  * The output will be markdown, with lots of HTML in it for styling
  * It will not be used for standalone documentation - it requires the website to render

### URLs for Testing
* Static cookbook: http://swharden.com/tmp/spcb
* Dynamic cookbook: https://swharden.com/scottplot/cookbooks/0.0.0-test

### Tasks
- [x] Add sections for cookbook recipes
- [x] Add sections for API/comments using Reflection and XML documentation
- [x] dynamically integrate cookbook into existing site
